# Generated by Django 2.1.2 on 2018-11-05 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SequencingRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.TextField(unique=True, verbose_name='Run ID')),
                ('path', models.FilePathField(allow_files=False, allow_folders=True, blank=True, path='/Users/kellys04/projects/tuco-test2/example-data/runs')),
                ('serial', models.TextField(blank=True)),
                ('run_num', models.TextField(blank=True)),
                ('flowcell', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SequencingSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.TextField(verbose_name='Sample ID')),
                ('sample_name', models.TextField(blank=True, verbose_name='Sample_Name')),
                ('i7_index', models.TextField(blank=True, verbose_name='I7_Index_ID')),
                ('index', models.TextField(blank=True)),
                ('sample_project', models.TextField(blank=True, verbose_name='Sample_Project')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('genome_folder', models.TextField(blank=True, verbose_name='GenomeFolder')),
                ('paired_normal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lims.SequencingSample')),
                ('run_id', models.ForeignKey(blank=True, db_column='run_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lims.SequencingRun')),
            ],
        ),
        migrations.CreateModel(
            name='SequencingSampleSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(blank=True, match='SampleSheet.csv', path='/Users/kellys04/projects/tuco-test2/example-data/samplesheets', recursive=True)),
                ('md5', models.TextField(blank=True, unique=True)),
                ('host', models.TextField(blank=True)),
                ('seq_type', models.CharField(choices=[('Archer', 'Archer'), ('NGS580', 'NGS580')], max_length=10)),
                ('iem_file_version', models.TextField(blank=True, verbose_name='IEMFileVersion')),
                ('investigator_name', models.TextField(blank=True, verbose_name='Investigator Name')),
                ('project_name', models.TextField(blank=True, verbose_name='Project Name')),
                ('experiment_name', models.TextField(blank=True, verbose_name='Experiment Name')),
                ('date', models.TextField(blank=True, verbose_name='Date')),
                ('workflow', models.TextField(blank=True, verbose_name='Workflow')),
                ('application', models.TextField(blank=True, verbose_name='Application')),
                ('assay', models.TextField(blank=True, verbose_name='Assay')),
                ('chemistry', models.TextField(blank=True, verbose_name='Chemistry')),
                ('adapter_sequence_read_1', models.TextField(blank=True, verbose_name='AdapterSequenceRead1')),
                ('adapter_sequence_read_2', models.TextField(blank=True, verbose_name='AdapterSequenceRead2')),
                ('hash', models.TextField(blank=True)),
                ('run_id', models.ForeignKey(blank=True, db_column='run_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lims.SequencingRun')),
            ],
        ),
        migrations.AddField(
            model_name='sequencingsample',
            name='samplesheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lims.SequencingSampleSheet'),
        ),
    ]
