# Generated by Django 2.1.2 on 2018-10-31 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SequencingRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Run_ID', models.TextField(unique=True)),
                ('Run_path', models.TextField(blank=True)),
                ('Sheet_path', models.TextField(blank=True)),
                ('Sheet_md5', models.TextField(blank=True)),
                ('Sheet_host', models.TextField(blank=True)),
                ('Seq_Type', models.TextField(blank=True)),
                ('Sequencer_Serial', models.TextField(blank=True)),
                ('Run_Num', models.TextField(blank=True)),
                ('Flowcell_ID', models.TextField(blank=True)),
                ('Date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SequencingSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sample_ID', models.TextField()),
                ('Sample_Name', models.TextField(blank=True)),
                ('Paired_Normal', models.TextField(blank=True)),
                ('I7_Index_ID', models.TextField(blank=True)),
                ('index', models.TextField(blank=True)),
                ('Sample_Project', models.TextField(blank=True)),
                ('Description', models.TextField(blank=True)),
                ('GenomeFolder', models.TextField(blank=True)),
                ('IEMFileVersion', models.TextField(blank=True)),
                ('Investigator_Name', models.TextField(blank=True)),
                ('Project_Name', models.TextField(blank=True)),
                ('Experiment_Name', models.TextField(blank=True)),
                ('Date', models.TextField(blank=True)),
                ('Workflow', models.TextField(blank=True)),
                ('Application', models.TextField(blank=True)),
                ('Assay', models.TextField(blank=True)),
                ('Chemistry', models.TextField(blank=True)),
                ('AdapterSequenceRead1', models.TextField(blank=True)),
                ('AdapterSequenceRead2', models.TextField(blank=True)),
                ('Sheet_path', models.TextField(blank=True)),
                ('Sheet_md5', models.TextField(blank=True)),
                ('Sheet_host', models.TextField(blank=True)),
                ('hash', models.TextField(blank=True, unique=True)),
                ('Run_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lims.SequencingRun')),
            ],
        ),
        migrations.CreateModel(
            name='SequencingSampleSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Run_ID', models.TextField(blank=True)),
                ('Sheet_path', models.TextField(blank=True)),
                ('Sheet_md5', models.TextField(blank=True, unique=True)),
                ('Sheet_host', models.TextField(blank=True)),
                ('hash', models.TextField(blank=True)),
            ],
        ),
    ]
